- hosts: localhost
  connection: local
  gather_facts: No
  remote_user: root

  vars_files:
    - ../group_vars/cred.yml

  pre_tasks: 
    - set_fact:
        timestamp: "{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
  tasks:
    - name: ec2 spin off
      ec2:
         key_name: jenkins
         group: default
         instance_type: t2.micro
         image: "{{ ami_id }}"
         region: "{{ aws_region }}"
         wait: true
         monitoring: yes
         exact_count: 1
         count_tag:
           Name: Demo
      register: bob
    - name: print ec2
      debug: msg="New Ec2 - {{ bob }}"

    - pause:
        minutes: 1
        
    - name: Wait for SSH to come up on "{{ bob.instances[0]['private_ip'] }}" 
      wait_for: host="{{ bob.instances[0]['private_ip'] }}" port=22 delay=60 timeout=320 state=started



    - name: Download the cloudwatch logs agent
      get_url:
        url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
        dest: /tmp/awslogs-agent-setup.py
        mode: 0750


    - name: Create /tmp/awslogs.conf
      copy:
        src: awslogs.conf
        dest: /tmp/awslogs.conf
        owner: root
        group: root
        mode: 0600

    - name: Run awslogs agent setup
      command: "{{awslogs_install_command}}"
      ignore_errors: yes
      register: awslogs_install



     




