- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - ../group_vars/aws-cred.yml

  pre_tasks: 
    - set_fact:
        timestamp: "{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
  tasks:
    - name: ec2 spin off
      ec2:
         key_name: jenkins
         group: default
         instance_type: t2.micro
         image: "{{ ami_id }}"
         region: "{{ aws_region }}"
         wait: true
         monitoring: yes
         exact_count: 1
         count_tag:
           Name: Demo
      register: bob
         



